name: i18

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  dist:
    permissions:
      contents: write
      repository-projects: write
    uses: ./.github/workflows/dist.yml
    secrets: inherit
