name: i18

on:
  push:
    tags:
      - "ver/[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  s3:
    permissions:
      contents: write
      repository-projects: write
    uses: ./.github/workflows/build.yml
    secrets: inherit
